### ISSUE TITLE
Transfer this repo out of putaindecode?

### ISSUE THREAD

**Issue by MoOx** [kud/ed-209#59]
Does not really make sense these days...
Repo name should be deprecated and use a new one.
Who want to take care of this repo?

**Comment by kud** [comment]
I'd like to take it back to my own 'orga' if p! doesn't want it anymore.

**Comment by Nyalab** [comment]
@madx has contributed to it, you and him should decide i think

**Comment by MoOx** [comment]
Yeah, when it's done, please go to settings, first page, at the bottom then transfert it to yourself or your orga.

**Comment by kud** [comment]
@madx is ok that I take it, we'll manage ourselves what we do with it.

**Comment by MoOx** [comment]
Nice. Have fun.

**Comment by kud** [comment]
Thank you. ;)
